### ISSUE TITLE
请教一下，怎样制作不需要server可以直接打开HTML看的结构，谢谢

### ISSUE THREAD

**Issue by jesse0917** [SuperZDev/echarts-doc-offline#4]

**Comment by SuperZDev** [comment]
你可以查看这篇文章[How to run thing locally](https://threejs.org/docs/#Manual/Introduction/How_to_run_things_locally)

提供的方法，主要是取消浏览器同源策略（有损安全性）
## Change local files security policy

### Safari

Enable the develop menu using the preferences panel, under Advanced -> "Show develop menu in menu bar"

Then from the safari "Develop" menu, select "Disable local file restrictions", it is also worth noting safari has some odd behaviour with caches, so it is advisable to use the "Disable caches" option in the same menu; if you are editing & debugging using safari.

### Chrome

Close all running Chrome instances first. The important word here is 'all'.

On Windows, you may check for Chrome instances using the Windows Task Manager. Alternatively, if you see a Chrome icon in the system tray, then you may open its context menu and click 'Exit'. This should close all Chrome instances.

Then start the Chrome executable with a command line flag:

chrome --allow-file-access-from-files
On Windows, probably the easiest is probably to create a special shortcut icon which has added the flag given above (right-click on shortcut -> properties -> target).

On Mac OSX, you can do this with

open /Applications/Google\ Chrome.app --args --allow-file-access-from-files
### Firefox

Go to
about:config
Find
security.fileuri.strict_origin_policy parameter
Set it to
false
